run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true

linters-settings:
  gci:
    local-prefixes: github.com/yitsushi/totp-cli
  goimports:
    local-prefixes: github.com/yitsushi/totp-cli
  staticcheck:
    go: "1.18"
  stylecheck:
    go: "1.18"
  govet:
    check-shadowing: true
  misspell:
    locale: US
  cyclop:
    max-complexity: 15
    skip-tests: true
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: false
  varnamelen:
    ignore-names:
      - ns
      - err
      - iv

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - goerr113
    - gocyclo
    - errcheck
    - gosec
    - dupl
    - funlen
    - scopelint
    - testpackage
    - varnamelen
  - path: commands/
    linters:
    - exhaustivestruct

linters:
  enable-all: true
  disable:
    - paralleltest
    - wrapcheck
    - exhaustivestruct
    - forbidigo
